# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    image: jtbai/php5-phpunit-xdebug
    links:
      - mysql-sdsdb
      - mysql-test-sdsdb
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html/
    restart: always
    ports:
      - 8080:80

  mysql-sdsdb:
    image: mariadb:10.0.33
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lolk1234
    ports:
      - 8036:3306
    volumes:
      - ./init/:/docker-entrypoint-initdb.d:ro

  mysql-test-sdsdb:
    image: mariadb:10.0.33
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lolk1234
    ports:
      - 7306:3306
    volumes:
      - ./init_test/:/docker-entrypoint-initdb.d:ro






